apiVersion: v1
kind: Namespace
metadata:
  name: paper-trading
  labels:
    name: paper-trading
    environment: prod
    purpose: paper-trading
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-ingestion
  labels:
    name: data-ingestion
    environment: prod
    purpose: data-ingestion