apiVersion: v1
kind: ServiceAccount
metadata:
  name: paper-trading-sa
  namespace: paper-trading
  annotations:
    iam.gke.io/gcp-service-account: paper-trading-k8s@PROJECT_ID.iam.gserviceaccount.com
  labels:
    environment: prod
    purpose: paper-trading
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: paper-trading
  name: paper-trading-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paper-trading-rolebinding
  namespace: paper-trading
subjects:
- kind: ServiceAccount
  name: paper-trading-sa
  namespace: paper-trading
roleRef:
  kind: Role
  name: paper-trading-role
  apiGroup: rbac.authorization.k8s.io